<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="jp-main-menu-manual-page col-lg-6 mx-auto">
    
        <h2 class="wt-page-title jp-main-menu-manual-page-title"><?= I18N::translate('webtrees Manual') ?></h2>

        <p><?= I18N::translate('The official webtrees documentation can be found at') ?><a href="https://webtrees.net/" target="_blank"> <strong>webtrees.net</strong></a> (<?= I18N::translate('see menu') ?> "Docs").</p>

        <p><?= I18N::translate('There are several manuals for webtrees:') ?></p>
        <ul>
            <li><?= I18N::translate('a manual in')?><a href="https://manu.jprodina.cz/" target="_blank"> <strong><?= I18N::translate('Czech language') ?></strong></a></li>
            <li><?= I18N::translate('a wiki-based manual in') ?><a href="https://wiki-de.genealogy.net/Webtrees_Handbuch" target="_blank"> <strong><?= I18N::translate('German language') ?></strong></a></li>
            <li><?= I18N::translate('a commercial manual in') ?><a href="https://richard-underwood.com/product/webtrees-manual/" target="_blank"> <strong><?= I18N::translate('English language') ?></strong></a></li>
        </ul>

</div>